# Mod Info
p_name = ImguiExample
p_id = imgui_example
p_group = com.darkmattrmaestro
p_desc = An example mod for Dear ImGui Integration that demonstrates basic use
p_author = DarkMattrMaestro
p_version = 1.0.6

# Cosmic Reach
cosmic_reach_version = 0.5.28-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.3-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

# Dear ImGui Integration
imgui_integration_version = 0.5.28-1.0.6