# Mod Info
p_name = ImguiIntegration
p_id = imgui_integration
p_group = org.tympanic
p_desc = Imgui Integration mod allows you to use imgui on any cosmic reach GameState
p_author = Tympanicblock61
p_version = 1.0.5

# Cosmic Reach
cosmic_reach_version = 0.5.26-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.3-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

# Imgui
lwjgl_version = 3.3.6
imgui_version = 1.90.0